version: '3.8'

services:
  products:
    build: ./produtos
    ports:
      - "3001:3001"
    networks:
      - ecommerce

  orders:
    build: ./pedidos
    ports:
      - "3002:3002"
    depends_on:
      - products
      - db
      - redis
    networks:
      - ecommerce

  payments:
    build: ./pagamentos
    ports:
      - "3003:3003"
    depends_on:
      - orders
    networks:
      - ecommerce

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - ecommerce

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ecommerce

networks:
  ecommerce:
